// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/serialization.js/src/js.debug.proto

package org.jetbrains.kotlin.serialization.js;

import com.google.protobuf.AbstractMessageLite;
import com.google.protobuf.AbstractParser;
import com.google.protobuf.ByteString;
import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.Descriptors;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.ExtensionRegistryLite;
import com.google.protobuf.GeneratedMessage;
import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Message;
import com.google.protobuf.MessageOrBuilder;
import com.google.protobuf.Parser;
import com.google.protobuf.RepeatedFieldBuilder;
import com.google.protobuf.UnknownFieldSet;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class DebugJsProtoBuf {
  private DebugJsProtoBuf() {}
  public static void registerAllExtensions(
      ExtensionRegistry registry) {
  }
  public interface FilesOrBuilder
      extends MessageOrBuilder {

    // repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    List<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry>
        getEntryList();
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry getEntry(int index);
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    int getEntryCount();
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    List<? extends org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder>
        getEntryOrBuilderList();
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder getEntryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Files}
   *
   * <pre>
   * For Kotlin/Javascript we reuse builtins serialization code, in which there are files for each package (see BuiltinsSerializationUtil)
   * </pre>
   */
  public static final class Files extends
      GeneratedMessage
      implements FilesOrBuilder {
    // Use Files.newBuilder() to construct.
    private Files(GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Files(boolean noInit) { this.unknownFields = UnknownFieldSet.getDefaultInstance(); }

    private static final Files defaultInstance;
    public static Files getDefaultInstance() {
      return defaultInstance;
    }

    public Files getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final UnknownFieldSet unknownFields;
    @Override
    public final UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Files(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      UnknownFieldSet.Builder unknownFields =
          UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entry_ = new ArrayList<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entry_.add(input.readMessage(org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (IOException e) {
        throw new InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = Collections.unmodifiableList(entry_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final Descriptors.Descriptor
        getDescriptor() {
      return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_descriptor;
    }

    protected GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.class, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.Builder.class);
    }

    public static Parser<Files> PARSER =
        new AbstractParser<Files>() {
      public Files parsePartialFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return new Files(input, extensionRegistry);
      }
    };

    @Override
    public Parser<Files> getParserForType() {
      return PARSER;
    }

    public interface FileEntryOrBuilder
        extends MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      String getName();
      /**
       * <code>required string name = 1;</code>
       */
      ByteString
          getNameBytes();

      // required bytes content = 2;
      /**
       * <code>required bytes content = 2;</code>
       */
      boolean hasContent();
      /**
       * <code>required bytes content = 2;</code>
       */
      ByteString getContent();
    }
    /**
     * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Files.FileEntry}
     */
    public static final class FileEntry extends
        GeneratedMessage
        implements FileEntryOrBuilder {
      // Use FileEntry.newBuilder() to construct.
      private FileEntry(GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private FileEntry(boolean noInit) { this.unknownFields = UnknownFieldSet.getDefaultInstance(); }

      private static final FileEntry defaultInstance;
      public static FileEntry getDefaultInstance() {
        return defaultInstance;
      }

      public FileEntry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final UnknownFieldSet unknownFields;
      @Override
      public final UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private FileEntry(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        UnknownFieldSet.Builder unknownFields =
            UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                content_ = input.readBytes();
                break;
              }
            }
          }
        } catch (InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
          throw new InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final Descriptors.Descriptor
          getDescriptor() {
        return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_descriptor;
      }

      protected GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.class, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder.class);
      }

      public static Parser<FileEntry> PARSER =
          new AbstractParser<FileEntry>() {
        public FileEntry parsePartialFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
          return new FileEntry(input, extensionRegistry);
        }
      };

      @Override
      public Parser<FileEntry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          ByteString bs =
              (ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          ByteString b =
              ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (ByteString) ref;
        }
      }

      // required bytes content = 2;
      public static final int CONTENT_FIELD_NUMBER = 2;
      private ByteString content_;
      /**
       * <code>required bytes content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes content = 2;</code>
       */
      public ByteString getContent() {
        return content_;
      }

      private void initFields() {
        name_ = "";
        content_ = ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasContent()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(CodedOutputStream output)
                          throws IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, content_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += CodedOutputStream
            .computeBytesSize(2, content_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws ObjectStreamException {
        return super.writeReplace();
      }

      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(
          ByteString data)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(
          ByteString data,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(byte[] data)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(
          byte[] data,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(InputStream input)
          throws IOException {
        return PARSER.parseFrom(input);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(
          InputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseDelimitedFrom(InputStream input)
          throws IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseDelimitedFrom(
          InputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(
          CodedInputStream input)
          throws IOException {
        return PARSER.parseFrom(input);
      }
      public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parseFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Files.FileEntry}
       */
      public static final class Builder extends
          GeneratedMessage.Builder<Builder>
         implements org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder {
        public static final Descriptors.Descriptor
            getDescriptor() {
          return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_descriptor;
        }

        protected GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.class, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder.class);
        }

        // Construct using org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          content_ = ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public Descriptors.Descriptor
            getDescriptorForType() {
          return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_descriptor;
        }

        public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry getDefaultInstanceForType() {
          return getDefaultInstance();
        }

        public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry build() {
          org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry buildPartial() {
          org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry result = new org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.content_ = content_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(Message other) {
          if (other instanceof org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry) {
            return mergeFrom((org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry other) {
          if (other == getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasContent()) {
            setContent(other.getContent());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasContent()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
          org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (InvalidProtocolBufferException e) {
            parsedMessage = (org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public ByteString
            getNameBytes() {
          Object ref = name_;
          if (ref instanceof String) {
            ByteString b =
                ByteString.copyFromUtf8(
                    (String) ref);
            name_ = b;
            return b;
          } else {
            return (ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required bytes content = 2;
        private ByteString content_ = ByteString.EMPTY;
        /**
         * <code>required bytes content = 2;</code>
         */
        public boolean hasContent() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes content = 2;</code>
         */
        public ByteString getContent() {
          return content_;
        }
        /**
         * <code>required bytes content = 2;</code>
         */
        public Builder setContent(ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          content_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes content = 2;</code>
         */
        public Builder clearContent() {
          bitField0_ = (bitField0_ & ~0x00000002);
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.serialization.js.Files.FileEntry)
      }

      static {
        defaultInstance = new FileEntry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.serialization.js.Files.FileEntry)
    }

    // repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;
    public static final int ENTRY_FIELD_NUMBER = 1;
    private List<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry> entry_;
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    public List<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry> getEntryList() {
      return entry_;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    public List<? extends org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder>
        getEntryOrBuilderList() {
      return entry_;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    public int getEntryCount() {
      return entry_.size();
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry getEntry(int index) {
      return entry_.get(index);
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
     */
    public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }

    private void initFields() {
      entry_ = Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(CodedOutputStream output)
                        throws IOException {
      getSerializedSize();
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(1, entry_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entry_.size(); i++) {
        size += CodedOutputStream
          .computeMessageSize(1, entry_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws ObjectStreamException {
      return super.writeReplace();
    }

    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(
        ByteString data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(
        ByteString data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(byte[] data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(
        byte[] data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(InputStream input)
        throws IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(
        InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseDelimitedFrom(InputStream input)
        throws IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseDelimitedFrom(
        InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(
        CodedInputStream input)
        throws IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parseFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Files}
     *
     * <pre>
     * For Kotlin/Javascript we reuse builtins serialization code, in which there are files for each package (see BuiltinsSerializationUtil)
     * </pre>
     */
    public static final class Builder extends
        GeneratedMessage.Builder<Builder>
       implements org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.FilesOrBuilder {
      public static final Descriptors.Descriptor
          getDescriptor() {
        return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_descriptor;
      }

      protected GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.class, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.Builder.class);
      }

      // Construct using org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (GeneratedMessage.alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (entryBuilder_ == null) {
          entry_ = Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entryBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public Descriptors.Descriptor
          getDescriptorForType() {
        return org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.internal_static_org_jetbrains_kotlin_serialization_js_Files_descriptor;
      }

      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files build() {
        org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files buildPartial() {
        org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files result = new org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files(this);
        int from_bitField0_ = bitField0_;
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entry_ = Collections.unmodifiableList(entry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(Message other) {
        if (other instanceof org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files) {
          return mergeFrom((org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files other) {
        if (other == getDefaultInstance()) return this;
        if (entryBuilder_ == null) {
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
        } else {
          if (!other.entry_.isEmpty()) {
            if (entryBuilder_.isEmpty()) {
              entryBuilder_.dispose();
              entryBuilder_ = null;
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entryBuilder_ = 
                GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntryFieldBuilder() : null;
            } else {
              entryBuilder_.addAllMessages(other.entry_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (InvalidProtocolBufferException e) {
          parsedMessage = (org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;
      private List<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry> entry_ =
        Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = new ArrayList<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry>(entry_);
          bitField0_ |= 0x00000001;
         }
      }

      private RepeatedFieldBuilder<
          org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder> entryBuilder_;

      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public List<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry> getEntryList() {
        if (entryBuilder_ == null) {
          return Collections.unmodifiableList(entry_);
        } else {
          return entryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public int getEntryCount() {
        if (entryBuilder_ == null) {
          return entry_.size();
        } else {
          return entryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry getEntry(int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);
        } else {
          return entryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
        } else {
          entryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.set(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder addEntry(org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
        } else {
          entryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(index, value);
          onChanged();
        } else {
          entryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder addEntry(
          org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder addAllEntry(
          Iterable<? extends org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry> values) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          addAll(values, entry_);
          onChanged();
        } else {
          entryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public Builder removeEntry(int index) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.remove(index);
          onChanged();
        } else {
          entryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder getEntryBuilder(
          int index) {
        return getEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder getEntryOrBuilder(
          int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);  } else {
          return entryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public List<? extends org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder>
           getEntryOrBuilderList() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilderList();
        } else {
          return Collections.unmodifiableList(entry_);
        }
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder addEntryBuilder() {
        return getEntryFieldBuilder().addBuilder(
            org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder addEntryBuilder(
          int index) {
        return getEntryFieldBuilder().addBuilder(
            index, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Files.FileEntry entry = 1;</code>
       */
      public List<org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder>
           getEntryBuilderList() {
        return getEntryFieldBuilder().getBuilderList();
      }
      private RepeatedFieldBuilder<
          org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new RepeatedFieldBuilder<
              org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntry.Builder, org.jetbrains.kotlin.serialization.js.DebugJsProtoBuf.Files.FileEntryOrBuilder>(
                  entry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.serialization.js.Files)
    }

    static {
      defaultInstance = new Files(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.serialization.js.Files)
  }

  private static Descriptors.Descriptor
    internal_static_org_jetbrains_kotlin_serialization_js_Files_descriptor;
  private static
    GeneratedMessage.FieldAccessorTable
      internal_static_org_jetbrains_kotlin_serialization_js_Files_fieldAccessorTable;
  private static Descriptors.Descriptor
    internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_descriptor;
  private static
    GeneratedMessage.FieldAccessorTable
      internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_fieldAccessorTable;

  public static Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n(core/serialization.js/src/js.debug.pro" +
      "to\022%org.jetbrains.kotlin.serialization.j" +
      "s\"z\n\005Files\022E\n\005entry\030\001 \003(\01326.org.jetbrain" +
      "s.kotlin.serialization.js.Files.FileEntr" +
      "y\032*\n\tFileEntry\022\014\n\004name\030\001 \002(\t\022\017\n\007content\030" +
      "\002 \002(\014B\021B\017DebugJsProtoBuf"
    };
    Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public ExtensionRegistry assignDescriptors(
            Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jetbrains_kotlin_serialization_js_Files_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jetbrains_kotlin_serialization_js_Files_fieldAccessorTable = new
            GeneratedMessage.FieldAccessorTable(
              internal_static_org_jetbrains_kotlin_serialization_js_Files_descriptor,
              new String[] { "Entry", });
          internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_descriptor =
            internal_static_org_jetbrains_kotlin_serialization_js_Files_descriptor.getNestedTypes().get(0);
          internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_fieldAccessorTable = new
            GeneratedMessage.FieldAccessorTable(
              internal_static_org_jetbrains_kotlin_serialization_js_Files_FileEntry_descriptor,
              new String[] { "Name", "Content", });
          return null;
        }
      };
    Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
